// <auto-generated />
namespace Ticketronic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Stringlength20to50 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stringlength20to50));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091849179_String length 20 to 50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
