// <auto-generated />
namespace Ticketronic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EventCascadeSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventCascadeSession));
        
        string IMigrationMetadata.Id
        {
            get { return "201605092130429_Event Cascade Session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
